-- generated by newgenasym Fri Sep 28 10:48:20 2012

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity res is
    port (    
	A:         INOUT  STD_LOGIC;    
	B:         INOUT  STD_LOGIC);
end res;
