-- generated by newgenasym Tue Dec 03 19:43:50 2013

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity led is
    port (    
	A:         INOUT  STD_LOGIC;    
	K:         INOUT  STD_LOGIC);
end led;
