-- generated by newgenasym Thu Sep 29 16:14:56 2016

library ieee;
use     ieee.std_logic_1164.all;
use     work.all;
entity bat_2p is
    port (    
	N:         INOUT  STD_LOGIC;    
	P:         INOUT  STD_LOGIC);
end bat_2p;
